inc:=-I../../Util -I../../lp
plugindir:=../../lp/plugin

all:temp.so
temp.so:main.c
	gcc -shared -fPIC -g -Wall -o $(plugindir)/$@ $^ $(inc)

inc:=-I../../Util -I../../lp
plugindir:=../../lp/plugin

all:temp.so
temp.so:main.c
	gcc -shared -fPIC -g -Wall -o $(plugindir)/$@ $^ $(inc)
